markdown: GFM

# Building settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

defaults:
  - scope:
      path: "offers/CS403-SP23/*"
      type: "pages"
    values:
        canvas-assig-pp11: "https://canvas.uw.edu/courses/1633262/assignments/8171250"
        canvas-assig-pp12: "https://canvas.uw.edu/courses/1633262/assignments/8171377"
